SELECT * FROM MARATONA_HOMENS
SELECT * FROM MARATONA_MULHERES

SELECT DISTINCT
MH.Country AS PAIS_HOMENS,
MM.Country AS PAIS_MULHERES
FROM
MARATONA_HOMENS MH
FULL JOIN
MARATONA_MULHERES MM
ON MH.Country = MM.Country

SELECT Country AS PAIS, COUNT(Country) AS TOTAL_VENCEDORES
FROM MARATONA_HOMENS
GROUP BY Country

SELECT Country AS PAIS, COUNT(Country) AS TOTAL_VENCEDORES
FROM MARATONA_MULHERES
GROUP BY Country

SELECT * FROM MARATONA_HOMENS

SELECT COUNT(Winner) AS TOTAL_MARATONAS, ROUND(SUM([Distance (KM)]) / COUNT(Winner), 2) AS MEDIA_KM FROM MARATONA_HOMENS 

