SELECT * FROM MARATONA_HOMENS
SELECT * FROM MARATONA_MULHERES

SELECT DISTINCT
MH.Country AS PAIS_HOMENS,
MM.Country AS PAIS_MULHERES
FROM
MARATONA_HOMENS MH
FULL JOIN
MARATONA_MULHERES MM
ON MH.Country = MM.Country

CREATE VIEW VENCEDORES_POR_PAIS AS
SELECT Country AS PAIS, COUNT(Country) AS TOTAL_VENCEDORES_HOMENS
FROM MARATONA_HOMENS
GROUP BY Country
ORDER BY TOTAL_VENCEDORES_HOMENS DESC

CREATE VIEW VENCEDORAS_POR_PAIS AS
SELECT Country AS PAIS, COUNT(Country) AS TOTAL_VENCEDORAS_MULHERES 
FROM MARATONA_MULHERES
WHERE Country IS NOT NULL
GROUP BY Country 
ORDER BY TOTAL_VENCEDORAS_HOMENS DESC

SELECT * FROM VENCEDORAS_POR_PAIS
SELECT * FROM VENCEDORES_POR_PAIS

SELECT COUNT(Winner) AS TOTAL_MARATONAS, ROUND(SUM([Distance (KM)]) / COUNT(Winner), 2) AS MEDIA_KM FROM MARATONA_HOMENS 
SELECT COUNT(Winner) AS TOTAL_MARATONAS, ROUND(SUM([Distance (KM)]) / COUNT(Winner), 2) AS MEDIA_KM FROM MARATONA_MULHERES

SELECT VP.PAIS, VP.TOTAL_VENCEDORAS_MULHERES,
ROUND((VP.TOTAL_VENCEDORAS_MULHERES) * MM.[Distance (KM)], 2) AS TOTAL_KM_PAIS
FROM VENCEDORAS_POR_PAIS VP
INNER JOIN MARATONA_MULHERES MM ON VP.PAIS = MM.Country
GROUP BY VP.TOTAL_VENCEDORAS_MULHERES, MM.[Distance (KM)], VP.PAIS
ORDER BY TOTAL_KM_PAIS DESC

SELECT VP.PAIS, VP.TOTAL_VENCEDORES_HOMENS,
ROUND((VP.TOTAL_VENCEDORES_HOMENS) * MM.[Distance (KM)], 2) AS TOTAL_KM_PAIS
FROM VENCEDORES_POR_PAIS VP
INNER JOIN MARATONA_MULHERES MM ON VP.PAIS = MM.Country
GROUP BY VP.TOTAL_VENCEDORES_HOMENS, MM.[Distance (KM)], VP.PAIS
ORDER BY TOTAL_KM_PAIS DESC
