SELECT * FROM MARATONA_HOMENS
SELECT * FROM MARATONA_MULHERES

SELECT DISTINCT
MH.Country AS PAIS_HOMENS,
MM.Country AS PAIS_MULHERES
FROM
MARATONA_HOMENS MH
FULL JOIN
MARATONA_MULHERES MM
ON MH.Country = MM.Country
