SELECT * FROM MARATONA_HOMENS
SELECT * FROM MARATONA_MULHERES

SELECT COUNT(*) FROM MARATONA_HOMENS
WHERE Country = 'United States'
SELECT COUNT(*) FROM MARATONA_MULHERES
WHERE Country = 'United States'

SELECT DISTINCT
MH.Country AS PAIS_HOMENS,
MM.Country AS PAIS_MULHERES
FROM
MARATONA_HOMENS MH
FULL JOIN
MARATONA_MULHERES MM
ON MH.Country = MM.Country
